
package com.acc.websrvices.rpc;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConverterPortType", targetNamespace = "http://jaxws.samples.geronimo.apache.org")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ConverterPortType {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://jaxws.samples.geronimo.apache.org/ConverterPortType/dollarToRupeesRequest", output = "http://jaxws.samples.geronimo.apache.org/ConverterPortType/dollarToRupeesResponse")
    public BigDecimal dollarToRupees(
        @WebParam(name = "arg0", partName = "arg0")
        BigDecimal arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://jaxws.samples.geronimo.apache.org/ConverterPortType/rupeesToEuroRequest", output = "http://jaxws.samples.geronimo.apache.org/ConverterPortType/rupeesToEuroResponse")
    public BigDecimal rupeesToEuro(
        @WebParam(name = "arg0", partName = "arg0")
        BigDecimal arg0);

}
