
package com.acc.websrvices.document;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConverterPortType", targetNamespace = "http://jaxws.samples.geronimo.apache.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConverterPortType {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dollarToRupees", targetNamespace = "http://jaxws.samples.geronimo.apache.org", className = "org.apache.geronimo.samples.jaxws.DollarToRupees")
    @ResponseWrapper(localName = "dollarToRupeesResponse", targetNamespace = "http://jaxws.samples.geronimo.apache.org", className = "org.apache.geronimo.samples.jaxws.DollarToRupeesResponse")
    @Action(input = "http://jaxws.samples.geronimo.apache.org/ConverterPortType/dollarToRupeesRequest", output = "http://jaxws.samples.geronimo.apache.org/ConverterPortType/dollarToRupeesResponse")
    public BigDecimal dollarToRupees(
        @WebParam(name = "arg0", targetNamespace = "")
        BigDecimal arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rupeesToEuro", targetNamespace = "http://jaxws.samples.geronimo.apache.org", className = "org.apache.geronimo.samples.jaxws.RupeesToEuro")
    @ResponseWrapper(localName = "rupeesToEuroResponse", targetNamespace = "http://jaxws.samples.geronimo.apache.org", className = "org.apache.geronimo.samples.jaxws.RupeesToEuroResponse")
    @Action(input = "http://jaxws.samples.geronimo.apache.org/ConverterPortType/rupeesToEuroRequest", output = "http://jaxws.samples.geronimo.apache.org/ConverterPortType/rupeesToEuroResponse")
    public BigDecimal rupeesToEuro(
        @WebParam(name = "arg0", targetNamespace = "")
        BigDecimal arg0);

}
